#!/bin/bash
# check the openvpn keys directory for new files and create the keys for new files.

die () {
    echo >&2 "$@"
    exit 1
}

[ `whoami` == 'root' ] || die "You must be root to do this."

if [ $(pidof -x openvpn-watchkeys| wc -w) -gt 2 ]; then 
    die "Cannot one more than 1 instance at a time."
fi

TARGET_DIR="/opt/openvpn_keys"

ls $TARGET_DIR | while read line
do
if [[ "$line" != ".unison"* && "$line" != *".tmp" && "$line" != *".zip" && ! -e "$TARGET_DIR/$line.zip" ]]
then
  openvpn-adduser $line
fi;
done
 
exit 0